site_name: Pintes Documentation
site_url: https://example.com
site_author: Formuna
site_description: Documentation for the Pintes project.
repo_url: https://github.com/FormunaGit/Pintes
repo_name: FormunaGit/Pintes
theme:
  name: theme
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
